name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      npm_config_python: C:\Python310\python.exe
      npm_config_msvs_version: 2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies and build native module
        run: |
          echo "安装 node-gyp..."
          npm install -g node-gyp

          echo "克隆并编译 ffi-napi..."
          git clone https://github.com/node-ffi-napi/node-ffi-napi.git
          cd node-ffi-napi
          node-gyp rebuild
          cd ..

          echo "安装项目依赖..."
          npm install ffi-napi@latest ref-napi@latest --save --force

      - name: Rebuild native modules for Electron
        run: |
          echo "使用 electron-rebuild 重建模块..."
          npx electron-rebuild --force

      - name: Build Electron App
        run: |
          echo "开始构建应用..."
          npm run build

      - name: Verify Build Output
        run: |
          echo "检查 dist 目录..."
          dir dist
          if (-Not (Test-Path "dist\*.exe")) {
            Write-Host "错误: dist 中未找到 EXE 文件"
            exit 1
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app
          path: dist/*.exe
          retention-days: 7
