# This is a basic workflow to help you get started with Actions

name: Build Electron App

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  pull_request:
    branches:
      - main  # 监听 main 分支的 PR 事件

jobs:
  build:
    runs-on: windows-latest
    env:
      npm_config_python: C:\Python310\python.exe
      npm_config_msvs_version: 2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install VS 2022 Build Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.3
          sdkver: 10.0.22000.0

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --global node-gyp
          npm install ffi-napi@latest ref-napi@latest --save --force

      - name: Rebuild modules
        run: npx electron-rebuild --force