# This is a basic workflow to help you get started with Actions

name: Build Electron App

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  pull_request:
    branches:
      - main  # 监听 main 分支的 PR 事件

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境来打包 EXE

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 获取代码

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16  # 选择 Node.js 版本

      - name: Install Dependencies
        run: npm install  # 使用 npm install 而不是 npm ci，因为没有 lock 文件


      - name: Build Electron App
        run: npm run build

      # 检查 dist 目录内容，确认是否生成 EXE
      - name: Verify Build Output
        run: |
          echo "Checking dist directory..."
          dir dist  # 在 Windows 环境下列出 dist 目录内容
          if (-Not (Test-Path "dist\*.exe")) {
            Write-Host "Error: No EXE file found in dist!"
            exit 1
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # 确保使用最新 v4 版本
        with:
          name: electron-app
          path: dist/*.exe  # 确保 EXE 输出路径正确
          retention-days: 7  # 7 天后自动删除