name: Build FFI Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # - name: Install Visual Studio Build Tools
    #   uses: microsoft/setup-msbuild@v1
    #   with:
    #     vs-version: '2022'
    #     msbuild-architecture: 'x64'

    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev electron-rebuild
        npx electron-rebuild

    - name: Build Electron App
      run: npm run build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-app
        path: dist/*.exe
        retention-days: 7 